version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: books_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - book-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  book-db-data: