-- V1__create_book_table.sql
-- Creates the 'book' table to match com.book.model.BookEntity

CREATE TABLE IF NOT EXISTS book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    price DOUBLE PRECISION,
    release_date DATE,
    genre VARCHAR(255)
);
